<?php

namespace App\Services;

class ContentKeyMapper
{
    static $labelMaps = [


        'report_content_detail' => [
            'en' => [
                'content_title'          => 'Content Section Title',
                'content_tags'           => 'Content Specific Tags',
                'description_heading'    => 'Description Heading',
                'description_text'       => 'Detailed Description',
                'summary_title'          => 'Summary Title',
                'summary_text'           => 'Summary Text',
                'challenge_title'        => 'Challenge Title',
                'challenge_text'         => 'Challenge Description',
                'solution_title'         => 'Solution Title',
                'solution_text'          => 'Solution Description',
                'long_term_impact_title' => 'Long-Term Impact Title',
                'long_term_impact_text'  => 'Long-Term Impact Description',
                'help_mini_title'        => 'Help Mini Title',
                'help_title'             => 'Help Title',
                'help_btn_text'          => 'Help button text',
                'image_help'             => 'Image Help',
                'reports_title'          => 'Reports Title',
            ],
            'es' => [
                'content_title'          => 'Título de la Sección de Contenido',
                'content_tags'           => 'Etiquetas Específicas del Contenido',
                'description_heading'    => 'Encabezado de Descripción',
                'description_text'       => 'Descripción Detallada',
                'summary_title'          => 'Título del Resumen',
                'summary_text'           => 'Texto del Resumen',
                'challenge_title'        => 'Título del Desafío',
                'challenge_text'         => 'Descripción del Desafío',
                'solution_title'         => 'Título de la Solución',
                'solution_text'          => 'Descripción de la Solución',
                'long_term_impact_title' => 'Título del Impacto a Largo Plazo',
                'long_term_impact_text'  => 'Descripción del Impacto a Largo Plazo',
                'help_mini_title'        => 'Mini título de Ayuda',
                'help_title'             => 'Título de ayuda',
                'help_btn_text'          => 'Texto botón de ayuda',
                'image_help'             => 'Imagen de Ayuda',
                'reports_title'          => 'Título Reports',
            ]
        ],

        'report_content' => [
            'en' => [
                'h1_title' => 'Main report title',
                'h3_1' => 'First subtitle',
                'paragraph_1' => 'First paragraph content...',
                'paragraph_2' => 'Second paragraph content...',
                'h3_2' => 'Second subtitle',
                'paragraph_3' => 'Third paragraph content...',
                'donate_title' => 'Donate title',
                'donate_text' => 'Donate text',
                'donate_button' => 'DONATE TO THIS PROJECT',
            ],
            'es' => [
                'h1_title' => 'Título principal del reporte',
                'h3_1' => 'Primer subtítulo',
                'paragraph_1' => 'Contenido del primer párrafo...',
                'paragraph_2' => 'Contenido del segundo párrafo...',
                'h3_2' => 'Segundo subtítulo',
                'paragraph_3' => 'Contenido del tercer párrafo...',
                'donate_title' => 'Ayuda a las personas necesitadas',
                'donate_text' => 'EMPIEZA A DONAR HOY, MARCA LA DIFERENCIA',
                'donate_button' => 'DONAR A ESTE PROYECTO',
            ],
        ],

        'edit_texts_projects' => [
            'en' => [
                'edit_title' => 'Edit Project',
                'title' => 'Title',
                'excerpt' => 'Excerpt',
                'donations_iframe' => 'Donations iframe (html)',
                'video_iframe' => 'Video iframe (Optional) (html)',
                'content' => 'Content',
                'meta_seo' => 'SEO Meta Tags',
                'seo_title' => 'SEO title',
                'seo_desc' => 'SEO Description',
                'seo_keywords' => 'SEO Keywords (Divided by commas)',
                'status' => 'Status',
                'publication' => 'Publication Date',
                'tags' => 'Tags',
                'social' => 'Redes Sociales',
                'featured_image' => 'Featured Image',
                'image_gallery' => 'Image Gallery',
                'delete_image' => 'Delete Image',
                'save_changes' => 'Save Changes',
                'discard_changes' => 'Discard Changes',
            ],
            'es' => [
                'edit_title' => 'Editar Proyecto',
                'title' => 'Título',
                'excerpt' => 'Extracto',
                'donations_iframe' => 'Iframe De Donaciones (html)',
                'video_iframe' => 'Iframe De Video (Opcional) (html)',
                'content' => 'Contenido',
                'meta_seo' => 'Meta etiquetas SEO',
                'seo_title' => 'Título SEO',
                'seo_desc' => 'Descripción SEO',
                'seo_keywords' => 'Palabras Clave SEO (Separadas por comas)',
                'status' => 'Estado',
                'publication' => 'Fecha de Publicación',
                'tags' => 'Etiquetas',
                'social' => 'Redes Sociales',
                'featured_image' => 'Imagen Destacada',
                'image_gallery' => 'Galería de Imágenes',
                'delete_image' => 'Eliminar imagen',
                'save_changes' => 'Guardar Cambios',
                'discard_changes' => 'Descartar Cambios',
            ]
        ],

        'project_content_details' => [
            'en' => [
                'special_tag'            => 'Special Tag',
                'content_title'          => 'Content Section Title',
                'description_heading'    => 'Description Heading',
                'description_text'       => 'Detailed Description',
                'summary_title'          => 'Summary Title',
                'summary_text'           => 'Summary Text',
                'help_mini_title'        => 'Help Mini Title',
                'help_title'             => 'Help Title',
                'help_btn_text'          => 'Help button text',
            ],
            'es' => [
                'special_tag'            => 'Tag Especial',
                'content_title'          => 'Título de la Sección de Contenido',
                'description_heading'    => 'Encabezado de Descripción',
                'description_text'       => 'Descripción Detallada',
                'summary_title'          => 'Título del Resumen',
                'summary_text'           => 'Texto del Resumen',
                'help_mini_title'        => 'Mini título de Ayuda',
                'help_title'             => 'Título de ayuda',
                'help_btn_text'          => 'Texto botón de ayuda',
            ]
        ],


        'edit_texts_pages' => [
            'en' => [
                'edit_title' => 'Edit Project',
                'title' => 'Title',
                'excerpt' => 'Excerpt',
                'donations_iframe' => 'Donations iframe (Optional) (html)',
                'video_iframe' => 'Video iframe (Optional) (html)',
                'content' => 'Content',
                'meta_seo' => 'SEO Meta Tags',
                'seo_title' => 'SEO title',
                'seo_desc' => 'SEO Description',
                'seo_keywords' => 'SEO Keywords (Divided by commas)',
                'status' => 'Status',
                'featured_image' => 'Featured Image',
                'delete_image' => 'Delete Image',
                'save_changes' => 'Save Changes',
                'discard_changes' => 'Discard Changes',
            ],
            'es' => [
                'edit_title' => 'Editar Proyecto',
                'title' => 'Título',
                'excerpt' => 'Extracto',
                'donations_iframe' => 'Iframe De Donaciones (Opcional) (html)',
                'video_iframe' => 'Iframe De Video (Opcional) (html)',
                'content' => 'Contenido',
                'meta_seo' => 'Meta etiquetas SEO',
                'seo_title' => 'Título SEO',
                'seo_desc' => 'Descripción SEO',
                'seo_keywords' => 'Palabras Clave SEO (Separadas por comas)',
                'status' => 'Estado',
                'featured_image' => 'Imagen Destacada',
                'delete_image' => 'Eliminar imagen',
                'save_changes' => 'Guardar Cambios',
                'discard_changes' => 'Descartar Cambios',
            ]
        ],

        // PAGES

        'home' => [
            'en' => [
                'h1_title' => 'H1 Title',
                'hero_text' => 'Hero Text',
                'help_subtitle' => 'Help Subtitle',
                'help_text' => 'Help Text', 
                'sponsors_title' => 'Sponsors Title',
                'about_mini_title' => 'About Mini Title',
                'about_subtitle' => 'About Subtitle',
                'image_about' => 'Image About',
                'about_text_1' => 'About Text 1',
                'about_text_2' => 'About Text 2',
                'values_title' => 'Values Title',
                'values_card_1_title' => 'Values Card 1 Title',
                'values_card_1_text' => 'Values Card 1 Text',
                'image_values_card_1' => 'Image Values Card 1',
                'values_card_2_title' => 'Values Card 2 Title',
                'values_card_2_text' => 'Values Card 2 Text',
                'image_values_card_2' => 'Image Values Card 2',
                'values_card_3_title' => 'Values Card 3 Title',
                'values_card_3_text' => 'Values Card 3 Text',
                'image_values_card_3' => 'Image Values Card 3',
                'certifications_title' => 'Certifications Title',
                'news_title' => 'News Title',
                'news_side_text' => 'News Side Text',
                'news_link' => 'News Link',
                'testimonials_mini_title' => 'Testimonials Mini Title',
                'testimonials_title' => 'Testimonials Title',
                'testimonials_side_text' => 'Testimonials Side Text',
                'testimonials_card_1_text' => 'Testimonials Card 1 Text',
                'image_testimonials_card_1' => 'Image Testimonials Card 1',
                'testimonials_card_2_text' => 'Testimonials Card 2 Text',
                'image_testimonials_card_2' => 'Image Testimonials Card 2',
                'testimonials_card_3_text' => 'Testimonials Card 3 Text',
                'image_testimonials_card_3' => 'Image Testimonials Card 3',
                'numbers_title' => 'Numbers Title',
                'numbers_text' => 'Numbers Text',
                'numbers_of_people_helped' => 'Numbers Of People Helped',
                'numbers_of_educated_children' => 'Numbers Of Educated Children',
                'numbers_of_volunteers' => 'Numbers Of Volunteers',
                'numbers_of_served_meal' => 'Numbers Of Served Meal',
                'call_to_action_title' => 'Call To Action Title',
                'call_to_action_text' => 'Call To Action Text',
                'call_to_action_card_1_title' => 'Call To Action Card 1 Title',
                'call_to_action_card_1_text' => 'Call To Action Card 1 Text',
                'call_to_action_card_2_title' => 'Call To Action Card 2 Title',
                'call_to_action_card_2_text' => 'Call To Action Card 2 Text',
                'call_to_action_card_3_title' => 'Call To Action Card 3 Title',
                'call_to_action_card_3_text' => 'Call To Action Card 3 Text',
                'image_call_to_action' => 'Image Call To Action'
            ],
            'es' => [
                'h1_title' => 'Título H1',
                'hero_text' => 'Texto Hero',
                'help_subtitle' => 'Subtítulo de Ayuda',
                'help_text' => 'Texto de Ayuda',
                'sponsors_title' => 'Título de Patrocinadores',
                'about_mini_title' => 'Mini Título Sobre',
                'about_subtitle' => 'Subtítulo Sobre',
                'image_about' => 'Imagen Sobre',
                'about_text_1' => 'Texto Sobre 1',
                'about_text_2' => 'Texto Sobre 2',
                'values_title' => 'Título de Valores',
                'values_card_1_title' => 'Título de Tarjeta de Valores 1',
                'values_card_1_text' => 'Texto de Tarjeta de Valores 1',
                'image_values_card_1' => 'Imagen de Tarjeta de Valores 1',
                'values_card_2_title' => 'Título de Tarjeta de Valores 2',
                'values_card_2_text' => 'Texto de Tarjeta de Valores 2',
                'image_values_card_2' => 'Imagen de Tarjeta de Valores 2',
                'values_card_3_title' => 'Título de Tarjeta de Valores 3',
                'values_card_3_text' => 'Texto de Tarjeta de Valores 3',
                'image_values_card_3' => 'Imagen de Tarjeta de Valores 3',
                'certifications_title' => 'Título de Certificaciones',
                'news_title' => 'Título de Noticias',
                'news_side_text' => 'Texto Lateral de Noticias',
                'news_link' => 'Enlace de Noticias',
                'testimonials_mini_title' => 'Mini Título de Testimonios',
                'testimonials_title' => 'Título de Testimonios',
                'testimonials_side_text' => 'Texto Lateral de Testimonios',
                'testimonials_card_1_text' => 'Texto de Tarjeta de Testimonios 1',
                'image_testimonials_card_1' => 'Imagen de Tarjeta de Testimonios 1',
                'testimonials_card_2_text' => 'Texto de Tarjeta de Testimonios 2',
                'image_testimonials_card_2' => 'Imagen de Tarjeta de Testimonios 2',
                'testimonials_card_3_text' => 'Texto de Tarjeta de Testimonios 3',
                'image_testimonials_card_3' => 'Imagen de Tarjeta de Testimonios 3',
                'numbers_title' => 'Título de Números',
                'numbers_text' => 'Texto de Números',
                'numbers_of_people_helped' => 'Números de Personas Ayudadas',
                'numbers_of_educated_children' => 'Números de Niños Educados',
                'numbers_of_volunteers' => 'Números de Voluntarios',
                'numbers_of_served_meal' => 'Números de Comidas Servidas',
                'call_to_action_title' => 'Título de Llamado a la Acción',
                'call_to_action_text' => 'Texto de Llamado a la Acción',
                'call_to_action_card_1_title' => 'Título de Tarjeta de Acción 1',
                'call_to_action_card_1_text' => 'Texto de Tarjeta de Acción 1',
                'call_to_action_card_2_title' => 'Título de Tarjeta de Acción 2',
                'call_to_action_card_2_text' => 'Texto de Tarjeta de Acción 2',
                'call_to_action_card_3_title' => 'Título de Tarjeta de Acción 3',
                'call_to_action_card_3_text' => 'Texto de Tarjeta de Acción 3',
                'image_call_to_action' => 'Imagen de Llamado a la Acción'
            ]
        ],

        'about' => [
            'en' => [
                'h1_title' => 'H1 Title',
                'hero_text' => 'Hero Text',
                'mission_title' => 'Mission Title',
                'mission_text' => 'Mission Text', 
                'floating_title' => 'Floating Title',
                'floating_text' => 'Floating Text',
                'image_floating_1' => 'Image Floating 1',
                'image_floating_2' => 'Image Floating 2',
                'help_title' => 'Help Title',
                'help_text' => 'Help Text',
                'certifications_title' => 'Certifications Title',
                'sponsors_title' => 'Sponsors Title',
                'values_card_1_title' => 'Values Card 1 Title',
                'values_card_1_text' => 'Values Card 1 Text',
                'image_values_card_1' => 'Image Values Card 1',
                'values_card_2_title' => 'Values Card 2 Title',
                'values_card_2_text' => 'Values Card 2 Text',
                'image_values_card_2' => 'Image Values Card 2',
                'values_card_3_title' => 'Values Card 3 Title',
                'values_card_3_text' => 'Values Card 3 Text',
                'image_values_card_3' => 'Image Values Card 3',
                'numbers_title' => 'Numbers Title',
                'numbers_text' => 'Numbers Text',
                'numbers_of_people_helped' => 'Numbers Of People Helped',
                'numbers_of_educated_children' => 'Numbers Of Educated Children',
                'numbers_of_volunteers' => 'Numbers Of Volunteers',
                'numbers_of_served_meal' => 'Numbers Of Served Meal',
                'reports_title' => 'Reports Title',
                'reports_text' => 'Reports Text',
                'image_report' => 'Image Report',
                'call_to_action_card_1_text' => 'Call To Action Card 1 Text',
                'call_to_action_card_2_title' => 'Call To Action Card 2 Title',
                'call_to_action_card_2_text' => 'Call To Action Card 2 Text',
                'call_to_action_card_3_title' => 'Call To Action Card 3 Title',
                'call_to_action_card_3_text' => 'Call To Action Card 3 Text',
            ],
            'es' => [
                'h1_title' => 'Título H1',
                'hero_text' => 'Texto Hero',
                'mission_title' => 'Título de Misión',
                'mission_text' => 'Texto de Misión', 
                'floating_title' => 'Título Flotante',
                'floating_text' => 'Texto Flotante',
                'image_floating_1' => 'Imagen Flotante 1',
                'image_floating_2' => 'Imagen Flotante 2',
                'help_title' => 'Título de Ayuda',
                'help_text' => 'Texto de Ayuda',
                'certifications_title' => 'Título de Certificaciones',
                'sponsors_title' => 'Título de Patrocinadores',
                'values_card_1_title' => 'Título de Tarjeta de Valores 1',
                'values_card_1_text' => 'Texto de Tarjeta de Valores 1',
                'image_values_card_1' => 'Imagen de Tarjeta de Valores 1',
                'values_card_2_title' => 'Título de Tarjeta de Valores 2',
                'values_card_2_text' => 'Texto de Tarjeta de Valores 2',
                'image_values_card_2' => 'Imagen de Tarjeta de Valores 2',
                'values_card_3_title' => 'Título de Tarjeta de Valores 3',
                'values_card_3_text' => 'Texto de Tarjeta de Valores 3',
                'image_values_card_3' => 'Imagen de Tarjeta de Valores 3',
                'numbers_title' => 'Título de Números',
                'numbers_text' => 'Texto de Números',
                'numbers_of_people_helped' => 'Números de Personas Ayudadas',
                'numbers_of_educated_children' => 'Números de Niños Educados',
                'numbers_of_volunteers' => 'Números de Voluntarios',
                'numbers_of_served_meal' => 'Números de Comidas Servidas',
                'reports_title' => 'Título de Reportes',
                'reports_text' => 'Texto de Reportes',
                'image_report' => 'Imagen de Reporte',
                'call_to_action_card_1_text' => 'Texto de Tarjeta de Acción 1',
                'call_to_action_card_2_title' => 'Título de Tarjeta de Acción 2',
                'call_to_action_card_2_text' => 'Texto de Tarjeta de Acción 2',
                'call_to_action_card_3_title' => 'Título de Tarjeta de Acción 3',
                'call_to_action_card_3_text' => 'Texto de Tarjeta de Acción 3',
            ]
        ],

        'news' => [
            'en' => [
                'h1_title' => 'H1 Title',
                'most_read_title' => 'Most Read Title',
                'search_text' => 'Search placeholder',
                'recent_articles_title' => 'Recent Articles',
            ],
            'es' => [
                'h1_title' => 'Título H1',
                'most_read_title' => 'Titulo más leídos',
                'search_text' => 'Placeholder de búsqueda',
                'recent_articles' => 'Artículos Recientes',
            ]
        ],

        'contact' => [
            'en' => [
                'h1_title' => 'H1 Title',
                'contact_text' => 'Contact Text',
                'name_label' => 'Name Label',
                'email_label' => 'Email Label',
                'subject_label' => 'Email Subject',
                'message_label' => 'Message Label',
                'submit' => 'Send Mail button',
                'our_contact_title' => 'Our Contact Title',
                'email_address_title' => 'Email address title',
                'address_title' => 'Address title',

                'call_to_action_card_1_title' => 'Call To Action Card 1 Title',
                'call_to_action_card_1_text' => 'Call To Action Card 1 Text',
                'call_to_action_card_2_title' => 'Call To Action Card 2 Title',
                'call_to_action_card_2_text' => 'Call To Action Card 2 Text',
                'call_to_action_card_3_title' => 'Call To Action Card 3 Title',
                'call_to_action_card_3_text' => 'Call To Action Card 3 Text',
            ],
            'es' => [
                'h1_title' => 'Título H1',
                'contact_text' => 'Texto de contacto',
                'name_label' => 'Campo de nombre',
                'email_label' => 'Campo de email',
                'subject_label' => 'Campo del tema del email',
                'message_label' => 'Campo del mensaje',
                'submit' => 'Botón de enviar mensaje',
                'call_to_action_card_1_title' => 'Título de Tarjeta de Acción 1',
                'call_to_action_card_1_text' => 'Texto de Tarjeta de Acción 1',
                'call_to_action_card_2_title' => 'Título de Tarjeta de Acción 2',
                'call_to_action_card_2_text' => 'Texto de Tarjeta de Acción 2',
                'call_to_action_card_3_title' => 'Título de Tarjeta de Acción 3',
                'call_to_action_card_3_text' => 'Texto de Tarjeta de Acción 3',
            ]
        ],

        'news' => [
            'en' => [
                'h1_title' => 'H1 Title',
                'most_read_title' => 'Most Read Title',
                'recent_articles' => 'Recent Articles',
            ],
            'es' => [
                'h1_title' => 'Título H1',
                'most_read_reports' => 'Título más leídos',
                'recent_articles' => 'Artículos Recientes',
            ]
        ],

        'donate' => [
            'en' => [
                'h1_color_title' => 'H1 Color Title',
                'h1_rest_title' => 'H1 Rest of the Title',
                'paragraph_1' => 'Paragraph 1',
                'text_title_1' => 'Text Title 1',
                'paragraph_2' => 'Paragraph 2',
                'paragraph_3' => 'Paragraph 3',
                'paragraph_4' => 'Paragraph 4',
                'text_title_2' => 'Text Title 2',
                'paragraph_5' => 'Paragraph 5',
                'paragraph_6' => 'Paragraph 6',
                'text_title_3' => 'Text Title 3',
                'paragraph_7' => 'Paragraph 7',
            ],
            'es' => [
                'h1_color_title' => 'Título H1 a Color',
                'h1_rest_title' => 'Resto del Título H1',
                'paragraph_1' => 'Párrafo 1',
                'text_title_1' => 'Título de Texto 1',
                'paragraph_2' => 'Párrafo 2',
                'paragraph_3' => 'Párrafo 3',
                'paragraph_4' => 'Párrafo 4',
                'text_title_2' => 'Título de Texto 2',
                'paragraph_5' => 'Párrafo 5',
                'paragraph_6' => 'Párrafo 6',
                'text_title_3' => 'Título de Texto 3',
                'paragraph_7' => 'Párrafo 7',
            ],
        ],

        'crypto' => [
            'en' => [
                'h1_title' => 'H1 Title',
                'paragraph_1' => 'Paragraph 1',
                'text_title' => 'Text Title',
                'paragraph_2' => 'Paragraph 2',
                'paragraph_3' => 'Paragraph 3',
                'paragraph_4' => 'Paragraph 4',
                'contact_title' => 'Contact Title',
                'contact_side_text_1' => 'Contact Side Text 1 (To fix)',
                'contact_side_text_2' => 'Contact Side Text 2',
            ],
            'es' => [
                'h1_title' => 'Título H1',
                'paragraph_1' => 'Párrafo 1',
                'text_title' => 'Text Title',
                'paragraph_2' => 'Párrafo 2',
                'paragraph_3' => 'Párrafo 3',
                'paragraph_4' => 'Párrafo 4',
                'contact_title' => 'Título contacto',
                'contact_side_text_1' => 'Texto Lateral Contacto 1 (To fix)',
                'contact_side_text_2' => 'Texto Lateral Contacto 2',
            ]
        ],

        'explore' => [
            'en' => [
                'h1_title' => 'H1 Title',
                'search_title' => 'Search Title',
                'search_placeholder' => 'Search Placeholder',
            ],
            'es' => [
                'h1_title' => 'Título H1',
                'search_title' => 'Título de Búsqueda',
                'search_placeholder' => 'Marcador de Posición de Búsqueda',
            ],
        ],


    ];

    public static function getLabel(string $pageType, string $key, string $locale): string
    {
        return self::$labelMaps[$pageType][$locale][$key] ?? ucfirst(str_replace('_', ' ', $key));
    }
}